import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

const Home = () => (
  <>
    <p>
      Click on link below to check the load size with differet import statements in the code.
    </p>
    <Link href="/all-countries">
      <a
        className="App-link"
        target="_blank"
        rel="noopener noreferrer"
      >
        All Countries
      </a>
    </Link>
    <Link href="/states-of-india">
      <a
        className="App-link"
        target="_blank"
        rel="noopener noreferrer"
      >
        States Of a Country (India)
      </a>
    </Link>
    <Link href="/cities-of-telangana">
      <a
        className="App-link"
        target="_blank"
        rel="noopener noreferrer"
      >
        Cities Of a State (Telangana)
      </a>
    </Link>
    <Link href="/countries-and-city">
      <a
        className="App-link"
        target="_blank"
        rel="noopener noreferrer"
      >
        Countries and Cities Of a State (Telangana)
      </a>
    </Link>
    <Link href="/countries-and-states">
      <a
        className="App-link"
        target="_blank"
        rel="noopener noreferrer"
      >
        All Countries and States of India only
      </a>
    </Link>
    <Link href="/states-and-cities">
      <a
        className="App-link"
        target="_blank"
        rel="noopener noreferrer"
      >
        All States and Cities of India only
      </a>
    </Link>
  </>
);
export default function App() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tree Shaking Demo | Country-State-City(npm)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Home></Home>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
